### PR TITLE
Add general programming dictionary

### PR DESCRIPTION
**Pull request by dimonster**

### CODE REVIEW

**Comment by morinted** [comment]
Nice, Di!

I'll review it in depth later and give it a whirl. I might have to fix my side of things because right now paragraphs of bulleted lists will be separated by two new lines instead of one like they should. That could also be fixed with one big paragraph like this: "- Point one\n- Point two\n- Point three". 

I'd also think that it should be renamed to something more reminiscent of the command-line.

I'm also okay with the dictionary files themselves not being in diffy format—I'm just using Plover's default myself. {flush} doesn't work with Plover, a true Plover flush stroke would probably just be "" or "{}". In any case, that's not necessary, but thanks for thinking of me :)

Finally, this is opinion and you don't have to address this, but I could see word boundary problems with an entry like "with get". Usually in the Plover default dictionary, such strokes would be formed like "W*/TKPWET" to be clear. Similar to "SKWR*/SOPB" in the default dictionary.

Let me know what you think. This is my first dictionary pull request so I'm very thankful that you took the time to submit this.

Cheers,
Ted

**Comment by dimonster** [comment]
Yeah, this has all been pieced together from random notes across the wiki, forums, Google group, etc. If only there was somewhere people shared their existing programming dictionaries so I had something to learn from... ;)

I didn't have the default dictionary until you gave me the updated release two days ago so 90% of my dictionaries are now redundant and I haven't had a chance to prune them all yet. Thanks for pointing out JSON being there. Maybe it's worth releasing an updated Mac release based on the old build just with updated dictionary? It seems like a decent number of newbies have also hit the missing punctuation problem. Or add that dictionary to stenodict and point all the getting started doco here?

I wasn't sure about wget (hoping "with get" was poor grammar and unlikely to show up), but I think it's the only one I formed like that. Have changed it with your feedback!

Stenodict is coming along nicely! It gave me pause a couple of times working out that it was expecting particular key names like why and how, and there being no actual hyperlinks to dictionaries on the index page (react?) but I had no actual issues at all! Ace project, I think this is really great.

**Comment by morinted** [comment]
Hey Di,

Just added a couple little changes to your dictionary and description to be a little in line with alignment and such. Check it out on the site now. Also added an author attribute.

Thanks for your PR

**Comment by dimonster** [comment]
Perfect! Thanks.

**Comment by morinted** [comment]
Thought for you: for the "-P" stroke, you could just define it as "." and git add . would still work, plus you'd be able to backspace through it unlike the command version.

**Comment by dimonster** [comment]
Oh, really? Neat! I think I had issues forcing the space in some instances. I'll see how I go with that version.

**Pull request merged**
